import type { IconType } from "react-icons";
import {
  SiHtml5,
  SiCss3,
  SiJavascript,
  SiTypescript,
  SiTailwindcss,
  SiShadcnui,
  SiMui,
  SiReact,
  SiRedux,
  SiNextdotjs,
  SiNodedotjs,
  SiNestjs,
  SiExpress,
  SiMongodb,
  SiDocker,
  SiVercel,
  SiGit,
  SiGithub,
  SiPostman,
  SiNpm,
  SiAnthropic,
  SiGithubactions,
  SiAmazonwebservices,
  SiPostgresql,
  SiRedis,
  SiSocketdotio,
  SiOpenai,
  SiFirebase,
  SiTwilio,
} from "react-icons/si";

export type Skill = {
  title: string;
  icon: IconType;
};

export const mySkills: Skill[] = [
  { title: "HTML", icon: SiHtml5 },
  { title: "CSS", icon: SiCss3 },
  { title: "JavaScript", icon: SiJavascript },
  { title: "TypeScript", icon: SiTypescript },
  { title: "Tailwind CSS", icon: SiTailwindcss },
  { title: "shadcn/ui", icon: SiShadcnui },
  { title: "Material UI", icon: SiMui },
  { title: "ReactJS", icon: SiReact },
  { title: "Redux", icon: SiRedux },
  { title: "NextJS", icon: SiNextdotjs },
  { title: "NodeJS", icon: SiNodedotjs },
  { title: "NestJS", icon: SiNestjs },
  { title: "ExpressJS", icon: SiExpress },
  { title: "MongoDB", icon: SiMongodb },
  { title: "Docker", icon: SiDocker },
  { title: "Vercel", icon: SiVercel },
  { title: "Git", icon: SiGit },
  { title: "GitHub", icon: SiGithub },
  { title: "Postman", icon: SiPostman },
  { title: "npm", icon: SiNpm },
  { title: "AI Integration", icon: SiAnthropic },
  { title: "Github Actions", icon: SiGithubactions },
  { title: "AWS", icon: SiAmazonwebservices },
  { title: "PostgreSQL", icon: SiPostgresql },
  { title: "Redis", icon: SiRedis },
  { title: "Socket.IO", icon: SiSocketdotio },
  { title: "OpenAI", icon: SiOpenai },
  { title: "Firebase", icon: SiFirebase },
  { title: "Twilio", icon: SiTwilio },
  { title: "MongoDB Compass", icon: SiMongodb },
];
