export const projects = [
    {
        "title": "Session Scribe | AI Meeting Transcription & Summaries",
        "slug": "session-scribe",
        "image": "https://res.cloudinary.com/dacvedc6z/image/upload/v1780836539/Screenshot_2026-06-07_174454_fqxyrd.png",
        "tagline": "A full‑stack AI meeting assistant that records calls, transcribes in real time, and turns conversations into structured notes and insights.",
        "overview": "Session Scribe is a full‑stack application built with a React 19 + Vite 6 frontend and a Node.js/Express backend backed by MongoDB. It uses Deepgram for live transcription, AWS S3 for media storage, Firebase for authentication, and Stripe for subscription billing. The product surface includes a marketing site and blog, an authenticated app with live transcription, AI summaries, audio notes, scheduled meetings, an article CMS, and an admin console — all styled with Tailwind CSS 4 and animated with Framer Motion.",
        "features": [
            "Real-time transcription via Deepgram with sub-second latency",
            "AI-generated meeting summaries with PDF export",
            "AI Insights dashboard with searchable history",
            "In-app chat assistant for querying past sessions",
            "Audio Notes for on-the-go dictation and structured notes",
            "Meeting scheduling with calendar integration",
            "Email digest recaps of past meetings",
            "Stripe-powered subscription plans and billing portal",
            "Firebase authentication with email/password and password reset",
            "Article CMS with create, edit, and publish workflows",
            "Admin dashboard for queries, feedback, and history",
            "Protected routes and role-based access control",
            "Responsive UI across mobile, tablet, and desktop"
        ],
        "techStack": [
            "React 19",
            "Vite 6",
            "Node.js",
            "Express",
            "MongoDB",
            "Tailwind CSS 4",
            "React Router 7",
            "Deepgram",
            "AWS S3",
            "Firebase",
            "Stripe",
            "Framer Motion",
            "Recharts",
            "@react-pdf/renderer",
            "Axios",
            "Lucide React",
            "React Icons",
            "React Toastify",
            "ESLint 9"
        ],
        "challenges": [
            "Coordinating a real-time audio + transcription pipeline across Deepgram.",
            "Handling long recording sessions and chunked uploads to AWS S3.",
            "Designing a flexible AI summary flow that scales across meeting types and lengths.",
            "Wiring Firebase auth, route guards, and session state across a multi-route SPA.",
            "Rendering large transcripts and summaries into performant, well-styled PDFs."
        ],
        "learnings": [
            "Real-time audio infrastructure with Deepgram and WebRTC.",
            "Integrating multiple third-party APIs into a single React app.",
            "Building accessible, animated SaaS UI patterns with Tailwind CSS and Framer Motion.",
            "Stripe subscription billing and customer portal flows in React.",
            "Multi-route admin and CMS architectures with React Router."
        ],
        "feedback": true,
        "links": {
            "live": "https://session-scribe-frontend.vercel.app/"
        }
    },
    {
        "title": "Interview Portal | AI Hiring & Interview Platform",
        "slug": "interview-portal",
        "image": "https://res.cloudinary.com/dacvedc6z/image/upload/v1780859649/Screenshot_2026-06-08_001326_jxurs3.png",
        "tagline": "A full‑stack, role‑based AI powered hiring platform with Firebase authentication, HR dashboards, job posting and applications handling with AI and candidate analytics.",
        "overview": "Interview Portal is a full‑stack AI powered recruitment system with a React 19 + Vite 7 frontend and a Node.js/Express + MongoDB backend. It supports candidates, HR teams, and admins through Firebase email/password and Google sign‑in, JWT‑backed protected routes, job posting and application workflows, candidate analytics, and a responsive Tailwind CSS UI connected to a dedicated backend API.",
        "features": [
            "AI-powered job posting, editing, and application management",
            "Email/password and Google Firebase authentication",
            "Role-based protected routes for candidate, HR, and admin users",
            "Live candidate dashboard with interview scheduling and status",
            "AI-powered resume review, documents, and candidate notes pages",
            "Analytics and HR reporting dashboards",
            "Responsive Tailwind CSS interface with React Router navigation"
        ],
        "techStack": [
            "React 19",
            "Vite 7",
            "Node.js",
            "Express",
            "MongoDB",
            "Tailwind CSS 4",
            "React Router 7",
            "Firebase Auth",
            "OpenAI API",
            "Axios",
            "Recharts",
            "JWT",
            "Lucide React"
        ],
        "challenges": [
            "Tweaking the LLM to match if the resume is a good fit for the job description, and providing a score for the resume.",
            "Implementing secure multi-role authentication and route guarding.",
            "Synchronizing Firebase Google sign-in with backend JWT sessions.",
            "Building a unified frontend for candidates, HR users, and admins."
        ],
        "learnings": [
            "Designing role-based React route and dashboard architecture.",
            "Integrating Firebase authentication with a custom API backend.",
            "Handling complex multi-user hiring workflows in a single frontend.",
            "Implementing real‑time interview experiences and analytics UI."
        ],
        "feedback": true,
        "links": {
            "live": "https://interview-portal-frontend-v1.vercel.app/"
        }
    },
    {
        title: 'PRISM | Multi-Agent AI Debate Platform',
        slug: 'prism',
        image: 'https://res.cloudinary.com/dacvedc6z/image/upload/v1780835994/Screenshot_2026-06-07_173528_rpc99n.png',
        tagline:
            'An AI debate platform where multiple LLM agents research, deliberate, challenge each other, and produce a final synthesized answer.',
        overview:
            'PRISM is a sophisticated multi-agent AI platform that orchestrates six AI agents through multiple rounds of debate and deliberation. The system combines web research, semantic memory, real-time communication, and AI synthesis to generate higher-quality answers than a single model. Built as a full-stack application with authentication, persistent conversations, and live streaming responses.',
        features: [
            '6-agent AI debate orchestration system',
            '2-round deliberation and challenge mechanics',
            'Real-time streaming responses with Socket.IO',
            'Semantic memory using Gemini embeddings',
            'Web research integration with Tavily',
            'Google OAuth 2.0 authentication',
            'JWT authentication with HttpOnly cookies',
            'Persistent conversation history',
        ],
        techStack: [
            'Next.js',
            'React 19',
            'Node.js',
            'Express.js',
            'MongoDB',
            'Mongoose',
            'Socket.IO',
            'Gemini',
            'Google OAuth',
            'JWT',
            'Tavily',
        ],
        challenges: [
            'Coordinating multiple AI agents in a structured debate workflow.',
            'Managing real-time communication between agents and users.',
            'Implementing semantic memory and contextual retrieval.',
            'Ensuring efficient orchestration while maintaining response quality.',
        ],
        learnings: [
            'Advanced AI agent architecture design.',
            'Semantic search and embeddings implementation.',
            'Real-time event-driven systems with Socket.IO.',
            'Building production-ready authentication systems.',
        ],
        feedback: true,
        links: {
            live: 'https://prism-web-v1.vercel.app',
            github: 'https://github.com/shahzaibalijamro/prism',
        },
    },

    {
        title: 'Pulse | Privacy-Focused Analytics SaaS',
        slug: 'pulse',
        image: 'https://res.cloudinary.com/dacvedc6z/image/upload/v1781034582/Screenshot_2026-06-10_004843_xuq7ml.png',
        tagline:
            'A lightweight analytics platform providing real-time website insights without compromising user privacy.',
        overview:
            'Pulse is a privacy-first analytics SaaS that allows businesses to track pageviews, visitors, devices, referrers, countries, and live events through a lightweight tracker script. The platform uses Redis buffering, MongoDB aggregation pipelines, and Socket.IO to provide real-time analytics while avoiding long-term personal data collection.',
        features: [
            'Real-time analytics dashboard',
            'Custom website tracker script',
            'Live visitor monitoring',
            'Device, country and referrer analytics',
            'Multi-tenant workspace architecture',
            'Redis-powered event buffering',
            'MongoDB aggregation pipelines',
            'Real-time dashboard updates with Socket.IO',
            'API key-based tracking system',
        ],
        techStack: [
            'Next.js',
            'TypeScript',
            'Node.js',
            'Express.js',
            'MongoDB',
            'Redis',
            'Socket.IO',
            'Tailwind CSS',
            'Recharts',
            'JWT',
        ],
        challenges: [
            'Designing a scalable analytics ingestion pipeline.',
            'Reducing database writes using Redis buffering.',
            'Building secure multi-tenant data isolation.',
            'Implementing real-time analytics updates efficiently.',
        ],
        learnings: [
            'Event-driven architecture design.',
            'Analytics aggregation strategies.',
            'Redis caching and buffering patterns.',
            'Multi-tenant SaaS application development.',
        ],
        feedback: true,
        links: {
            live: 'https://pulse-steel-two.vercel.app',
            github: 'https://github.com/shahzaibalijamro/pulse',
        },
    },
    {
        title: 'Luxe | Multi-Vendor Ecommerce Marketplace API',
        slug: 'luxe',
        image: 'https://res.cloudinary.com/dacvedc6z/image/upload/v1780836284/Screenshot_2026-06-07_174320_stz9cl.png',
        tagline:
            'A production-grade REST API for a multi-vendor ecommerce platform with seller onboarding, media management, and Stripe payments.',
        overview:
            'Luxe is a full-featured ecommerce backend that powers a multi-vendor marketplace where sellers can open stores, manage products, and fulfill orders while buyers browse, review, and purchase. The API is built with NestJS 11 and TypeORM on top of PostgreSQL, with Cloudinary handling media, Stripe Connect handling seller onboarding and registration fees, and Nodemailer driving transactional email. Authentication supports both email/password and Google OAuth, with JWTs in HttpOnly cookies, role-based authorization, two-tier rate limiting, and a fully documented OpenAPI 3 surface.',
        features: [
            'Multi-vendor seller onboarding with Stripe Connect registration fees',
            'Email/password and Google OAuth 2.0 authentication',
            'JWT authentication with HttpOnly cookies and token versioning',
            'Role-based authorization for USER, SELLER, and ADMIN',
            'Product catalog with image and video media management',
            'Many-to-many tag system for product categorization',
            'Per-user cart with quantity updates and clearing',
            'Order creation and per-item fulfillment status for sellers',
            'Verified-buyer reviews with star ratings and media uploads',
            'Favorites with per-product counts and bulk ID listing',
            'Multiple contact information entries per user for shipping',
            'Cloudinary integration for uploads, replacements, and deletion',
            'Branded transactional email templates for password resets',
            'Two-tier rate limiting with per-route opt-out',
            'Helmet, HPP, and CORS allow-list security hardening',
            'Full OpenAPI 3 documentation via Swagger UI at /docs',
        ],
        techStack: [
            'NestJS 11',
            'TypeScript 5.7',
            'Node.js 20',
            'TypeORM 0.3',
            'PostgreSQL 16',
            'Supabase',
            'Passport.js',
            'JWT',
            'Google OAuth 2.0',
            'bcrypt',
            'Stripe Connect',
            'Cloudinary',
            'Nodemailer',
            'Multer',
            'class-validator',
            'class-transformer',
            'Helmet',
            'HPP',
            '@nestjs/throttler',
            '@nestjs/swagger',
        ],
        challenges: [
            'Designing a multi-vendor data model where orders span multiple sellers with per-item fulfillment.',
            'Implementing seller registration flows with Stripe Connect and a one-time onboarding fee.',
            'Coordinating media uploads, replacements, and deletions across Cloudinary and TypeORM.',
            'Enforcing verified-buyer review eligibility while keeping the read path efficient.',
            'Building two-tier rate limiting that protects auth flows without throttling legitimate traffic.',
        ],
        learnings: [
            'Deep NestJS architecture with custom guards, interceptors, and decorators.',
            'TypeORM relationship modeling including one-to-one, one-to-many, and many-to-many.',
            'Stripe Connect Express onboarding and payment intent lifecycles.',
            'Serverless-ready NestJS deployment via a Vercel-compatible wrapper.',
            'Production security patterns: Helmet, HPP, validation pipes, and rate limiting.',
        ],
        feedback: true,
        links: {
            live: 'https://luxe-ecommerce-store-v1.vercel.app/',
            github: 'https://github.com/shahzaibalijamro/mastering-nestjs',
        },
    },
    {
        title: 'Jamro Tools | All-in-One Utility Platform',
        slug: 'jamro-tools',
        image: 'https://res.cloudinary.com/dacvedc6z/image/upload/v1780836235/Screenshot_2026-06-07_174202_yeqbrl.png',
        tagline:
            'A growing collection of hundreds of online utilities built for speed, privacy, and accessibility.',
        overview:
            'Jamro Tools is a large-scale utility platform that aims to provide calculators, converters, developer tools, generators, PDF utilities, image tools, and more in a single place. The platform is built with a focus on performance, responsive design, and privacy-first processing.',
        features: [
            'Hundreds of planned utility tools',
            'Calculator and converter ecosystem',
            'Developer-focused tools',
            'SEO and content utilities',
            'Image and PDF processing tools',
            'Fast and responsive interface',
            'SEO optimized architecture',
            'Privacy-first approach',
        ],
        techStack: [
            'Next.js 16',
            'React 19',
            'TypeScript',
            'Tailwind CSS',
            'Google Tag Manager',
        ],
        challenges: [
            'Designing an architecture that can support hundreds of tools.',
            'Maintaining performance as the platform scales.',
            'Building reusable tool-generation patterns.',
            'Optimizing SEO across large numbers of pages.',
        ],
        learnings: [
            'Large-scale Next.js application architecture.',
            'Programmatic SEO strategies.',
            'Reusable component system design.',
            'Performance optimization techniques.',
        ],
        feedback: false,
        links: {
            live: 'https://jamro-tools.vercel.app',
            github: 'https://github.com/shahzaibalijamro/jamro-tools',
        },
    },


]