export const projects = [
  {
    title: 'PRISM | Multi-Agent AI Debate Platform',
    slug: 'prism',
    tagline:
      'An AI debate platform where multiple LLM agents research, deliberate, challenge each other, and produce a final synthesized answer.',
    overview:
      'PRISM is a sophisticated multi-agent AI platform that orchestrates six AI agents through multiple rounds of debate and deliberation. The system combines web research, semantic memory, real-time communication, and AI synthesis to generate higher-quality answers than a single model. Built as a full-stack application with authentication, persistent conversations, and live streaming responses.',
    features: [
      '6-agent AI debate orchestration system',
      '2-round deliberation and challenge mechanics',
      'Real-time streaming responses with Socket.IO',
      'Semantic memory using Gemini embeddings',
      'Web research integration with Tavily',
      'Google OAuth 2.0 authentication',
      'JWT authentication with HttpOnly cookies',
      'Persistent conversation history',
    ],
    techStack: [
      'Next.js',
      'React 19',
      'Node.js',
      'Express.js',
      'MongoDB',
      'Mongoose',
      'Socket.IO',
      'Gemini',
      'Google OAuth',
      'JWT',
      'Tavily',
    ],
    challenges: [
      'Coordinating multiple AI agents in a structured debate workflow.',
      'Managing real-time communication between agents and users.',
      'Implementing semantic memory and contextual retrieval.',
      'Ensuring efficient orchestration while maintaining response quality.',
    ],
    learnings: [
      'Advanced AI agent architecture design.',
      'Semantic search and embeddings implementation.',
      'Real-time event-driven systems with Socket.IO.',
      'Building production-ready authentication systems.',
    ],
    feedback: true,
    links: {
      live: 'https://prism-web-v1.vercel.app',
      github: 'https://github.com/shahzaibalijamro/prism',
    },
  },

  {
    title: 'Pulse | Privacy-Focused Analytics SaaS',
    slug: 'pulse',
    tagline:
      'A lightweight analytics platform providing real-time website insights without compromising user privacy.',
    overview:
      'Pulse is a privacy-first analytics SaaS that allows businesses to track pageviews, visitors, devices, referrers, countries, and live events through a lightweight tracker script. The platform uses Redis buffering, MongoDB aggregation pipelines, and Socket.IO to provide real-time analytics while avoiding long-term personal data collection.',
    features: [
      'Real-time analytics dashboard',
      'Custom website tracker script',
      'Live visitor monitoring',
      'Device, country and referrer analytics',
      'Multi-tenant workspace architecture',
      'Redis-powered event buffering',
      'MongoDB aggregation pipelines',
      'Real-time dashboard updates with Socket.IO',
      'API key-based tracking system',
    ],
    techStack: [
      'Next.js',
      'TypeScript',
      'Node.js',
      'Express.js',
      'MongoDB',
      'Redis',
      'Socket.IO',
      'Tailwind CSS',
      'Recharts',
      'JWT',
    ],
    challenges: [
      'Designing a scalable analytics ingestion pipeline.',
      'Reducing database writes using Redis buffering.',
      'Building secure multi-tenant data isolation.',
      'Implementing real-time analytics updates efficiently.',
    ],
    learnings: [
      'Event-driven architecture design.',
      'Analytics aggregation strategies.',
      'Redis caching and buffering patterns.',
      'Multi-tenant SaaS application development.',
    ],
    feedback: true,
    links: {
      live: 'https://pulse-steel-two.vercel.app',
      github: 'https://github.com/shahzaibalijamro/pulse',
    },
  },

  {
    title: 'Jamro Tools | All-in-One Utility Platform',
    slug: 'jamro-tools',
    tagline:
      'A growing collection of hundreds of online utilities built for speed, privacy, and accessibility.',
    overview:
      'Jamro Tools is a large-scale utility platform that aims to provide calculators, converters, developer tools, generators, PDF utilities, image tools, and more in a single place. The platform is built with a focus on performance, responsive design, and privacy-first processing.',
    features: [
      'Hundreds of planned utility tools',
      'Calculator and converter ecosystem',
      'Developer-focused tools',
      'SEO and content utilities',
      'Image and PDF processing tools',
      'Fast and responsive interface',
      'SEO optimized architecture',
      'Privacy-first approach',
    ],
    techStack: [
      'Next.js 16',
      'React 19',
      'TypeScript',
      'Tailwind CSS',
      'Google Tag Manager',
    ],
    challenges: [
      'Designing an architecture that can support hundreds of tools.',
      'Maintaining performance as the platform scales.',
      'Building reusable tool-generation patterns.',
      'Optimizing SEO across large numbers of pages.',
    ],
    learnings: [
      'Large-scale Next.js application architecture.',
      'Programmatic SEO strategies.',
      'Reusable component system design.',
      'Performance optimization techniques.',
    ],
    feedback: false,
    links: {
      live: 'https://jamro-tools.vercel.app',
      github: 'https://github.com/shahzaibalijamro/jamro-tools',
    },
  },
  {
    title: 'Luxe | Multi-Vendor Ecommerce Marketplace API',
    slug: 'luxe',
    tagline:
      'A production-grade REST API for a multi-vendor ecommerce platform with seller onboarding, media management, and Stripe payments.',
    overview:
      'Luxe is a full-featured ecommerce backend that powers a multi-vendor marketplace where sellers can open stores, manage products, and fulfill orders while buyers browse, review, and purchase. The API is built with NestJS 11 and TypeORM on top of PostgreSQL, with Cloudinary handling media, Stripe Connect handling seller onboarding and registration fees, and Nodemailer driving transactional email. Authentication supports both email/password and Google OAuth, with JWTs in HttpOnly cookies, role-based authorization, two-tier rate limiting, and a fully documented OpenAPI 3 surface.',
    features: [
      'Multi-vendor seller onboarding with Stripe Connect registration fees',
      'Email/password and Google OAuth 2.0 authentication',
      'JWT authentication with HttpOnly cookies and token versioning',
      'Role-based authorization for USER, SELLER, and ADMIN',
      'Product catalog with image and video media management',
      'Many-to-many tag system for product categorization',
      'Per-user cart with quantity updates and clearing',
      'Order creation and per-item fulfillment status for sellers',
      'Verified-buyer reviews with star ratings and media uploads',
      'Favorites with per-product counts and bulk ID listing',
      'Multiple contact information entries per user for shipping',
      'Cloudinary integration for uploads, replacements, and deletion',
      'Branded transactional email templates for password resets',
      'Two-tier rate limiting with per-route opt-out',
      'Helmet, HPP, and CORS allow-list security hardening',
      'Full OpenAPI 3 documentation via Swagger UI at /docs',
    ],
    techStack: [
      'NestJS 11',
      'TypeScript 5.7',
      'Node.js 20',
      'TypeORM 0.3',
      'PostgreSQL 16',
      'Supabase',
      'Passport.js',
      'JWT',
      'Google OAuth 2.0',
      'bcrypt',
      'Stripe Connect',
      'Cloudinary',
      'Nodemailer',
      'Multer',
      'class-validator',
      'class-transformer',
      'Helmet',
      'HPP',
      '@nestjs/throttler',
      '@nestjs/swagger',
    ],
    challenges: [
      'Designing a multi-vendor data model where orders span multiple sellers with per-item fulfillment.',
      'Implementing seller registration flows with Stripe Connect and a one-time onboarding fee.',
      'Coordinating media uploads, replacements, and deletions across Cloudinary and TypeORM.',
      'Enforcing verified-buyer review eligibility while keeping the read path efficient.',
      'Building two-tier rate limiting that protects auth flows without throttling legitimate traffic.',
    ],
    learnings: [
      'Deep NestJS architecture with custom guards, interceptors, and decorators.',
      'TypeORM relationship modeling including one-to-one, one-to-many, and many-to-many.',
      'Stripe Connect Express onboarding and payment intent lifecycles.',
      'Serverless-ready NestJS deployment via a Vercel-compatible wrapper.',
      'Production security patterns: Helmet, HPP, validation pipes, and rate limiting.',
    ],
    feedback: true,
    links: {
      live: 'https://luxe-ecommerce-store-v1.vercel.app/',
      github: 'https://github.com/shahzaibalijamro/mastering-nestjs',
    },
  },

];
